@startuml

!$CliLabel = "CLI"
!$CliTech = "Docopt"
!$CliDef = "Command line utility that teaches the user how to use the system and parses user input."

!$ValidatorLabel = "Validator"
!$ValidatorTech = "Cerberus"
!$ValidatorDef = "Validates that the commands that where passed to the CLI respect their schema."

!$KernelLabel = "Javamop"
!$KernelTech = "python"
!$KernelDef = "Python class that handles javamop files and parses them to a data structure."

!$FilesystemLabel = "Filesystem"
!$FilesystemTech = "python"
!$FilesystemDef = "Handles filesystem operation such as searching/copying files."

!$UserToCli = "Uses"
!$CliToValidator = "Uses"
!$CliToKernel = "Passes the input file for the kernel."
!$CliToFilesystem = "Passes violatios to be copied/searched for."

!$InternalCall = "Calls"

@enduml
