@startuml

!$CliLabel = "CLI"
!$CliTech = "Docopt"
!$CliDef = "Command line utility that teaches the user how to use the system and parses user input."

!$UserToCli = "Uses"

!$InternalCall = "Calls"

@enduml
